CREATE TABLE pessoa
(
    id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cpf  VARCHAR(11)  NOT NULL,
    nome VARCHAR(250) NOT NULL
);

CREATE TABLE produto
(
    id             INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descricao      VARCHAR(50)    NOT NULL,
    valor_unitario NUMERIC(10, 2) NOT NULL
);

CREATE TABLE pedido
(
    id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pessoa_id  INTEGER NOT NULL REFERENCES pessoa(id) ON DELETE CASCADE
);

CREATE TABLE pedidoitem
(
    id           INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pedido_id    INTEGER NOT NULL REFERENCES pedido(id)  ON DELETE CASCADE,
    produto_id   INTEGER NOT NULL REFERENCES produto(id),
    quantidade   INTEGER NOT NULL
);
